#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/empiezo;NON_KEYWORDS=USER;MODE=MySQL
#    username: sa
#    driver-class-name: org.h2.Driver
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/empiezo?characterEncoding=UTF-8&serverTimezone=UTC
    username: empiezo
    password: 159125
  sql:
    init:
      mode: always
  session:
    storage-type: redis
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      type:
        descriptor:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1000202227745-j6gubevipbqs77p1lursbu12sipoi0v9.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
  devtools:
    livereload:
      enable: true
    restart:
      enable: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            blind: trace
file:
  path: /Users/pedro/study/profileImage
springdoc:
  packages-to-scan: com.empiezo.empiezo.controller

  


